#!/usr/bin/env sh

# Example usage:
# git grep --files-with-matches 'should_autogenerate_check_in_report' | xargs sed -i '' 's/should_autogenerate_check_in_report/should_autogenerate_bulk_report_from_inactivity/g'

git grep --files-with-matches "$1" "${@:3}" | xargs sed -i '' "s/$1/$2/g"
